---
- name: Launch application container
  docker_container:
    name: simple-api-container
    image: ineshjz04/tp-devops-simple-api
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/db"
      SPRING_DATASOURCE_USERNAME: "usr"
      SPRING_DATASOURCE_PASSWORD: "pwd"
    state: started
    restart_policy: always

