---
- name: Launch application container
  docker_container:
    name: backend
    image: ineshjz04/tp-devops-simple-api
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: "{{ spring_datasource_url }}"
      SPRING_DATASOURCE_USERNAME: "{{ spring_datasource_username }}"
      SPRING_DATASOURCE_PASSWORD: "{{ spring_datasource_password }}"
    state: started
    restart_policy: always

  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
