name: CD - Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_INESHJZ04 }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push database image
        working-directory: sample-application-students-master/database
        run: |
          docker build -t ineshjz04/tp-devops-database .
          docker push ineshjz04/tp-devops-database

      - name: Build and push api image
        working-directory: sample-application-students-master/sample-application-backend
        run: |
          docker build -t ineshjz04/tp-devops-simple-api .
          docker push ineshjz04/tp-devops-simple-api

      - name: Build and push httpd image
        working-directory: sample-application-students-master/sample-application-frontend
        run: |
          docker build -t ineshjz04/tp-devops-httpd .
          docker push ineshjz04/tp-devops-httpd