name: CD - Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Build and push database image
        run: |
          docker build -t ineshjz04/tp-devops-database ./sample-application-students-master/database
          docker push ineshjz04/tp-devops-database

      - name: Build and push api image
        run: |
          docker build -t ineshjz04/tp-devops-simple-api ./sample-application-students-master/sample-application-backend
          docker push ineshjz04/tp-devops-simple-api

      - name: Build and push httpd image
        run: |
          docker build -t ineshjz04/tp-devops-httpd ./sample-application-students-master/sample-application-frontend
          docker push ineshjz04/tp-devops-httpd